### ISSUE TITLE
how to get the log level?

### ISSUE THREAD

**Issue by Xsmael** [guithess/syslog-server#2]
Hello, may I know how to get the log level of a received log message ?

Thank You!

**Comment by guithess** [comment]
Hi Xsmael, as there are different syslog message formats this lib currently does not provide any default parser, so you should parse the message yourself to get the log level.

A fast search listed some libraries that claims to parse syslog messages compliant to different versions of the RFC.

Check out the following libs and see if one of them suit your needs:

- glossy
- syslog-parse
- syslog
- syslogd

Please note I did not try any of the libs above and that none of are them related to this project.

Hope this help you towards the right direction!
